version: "3.8"
services:
  eureka-server:
    build: ./eureka-server/
    container_name: eureka-server
    restart: always
    ports:
      - "8761:8761"
  countries-application:
    build: ./CountriesApplication/
    depends_on:
      - eureka-server
    container_name: countries-application
    restart: always
  covid-application:
    build: ./CovidApplication/
    depends_on:
      - eureka-server
    container_name: covid-application
    restart: always
  aggregator-application:
    build: ./AggregatorApplication/
    depends_on:
      - countries-application
      - covid-application
      - eureka-server
    container_name: aggregator-application
    restart: always
  apigateway:
    build: ./ApiGatewayApplication/
    depends_on:
      - aggregator-application
    container_name: api-gateway
    restart: always
    ports:
      - "80:80"
